In [2]:
import pandas as pd
import numpy as np
from utils import *

In [3]:
data = pd.read_csv('data/Train.csv')

In [28]:
4 * np.eye(3)

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [5]:
movies = data['Movie_ID_Alias'].nunique()
users = data['User_ID_Alias'].nunique()
print(f'Movies: {movies}')
print(f'Users: {users}')

Movies: 3224
Users: 6040


In [6]:
data['Movie_ID_Alias'].max()

3706

In [7]:
validation_data = pd.read_csv('data/Validation.csv')
validation_data

User_ID_Alias  Movie_ID_Alias  Ratings_Rating
0                 1             742               4
1                 2             470               4
2                 3            2177               5
3                 4            1647               4
4                 5            2159               2
...             ...             ...             ...
6035           6036             500               3
6036           6037            1105               1
6037           6038            1376               2
6038           6039             500               4
6039           6040            1996               3

[6040 rows x 3 columns]

In [8]:
# print num of movies and users in validation set
movies = validation_data['Movie_ID_Alias'].nunique()
users = validation_data['User_ID_Alias'].nunique()
print(f'Movies: {movies}')
print(f'Users: {users}')

Movies: 711
Users: 6040


In [15]:
t,v = get_data()

In [16]:
v[:,0]

array([   0,    1,    2, ..., 6037, 6038, 6039])

In [18]:
print(v.shape)
# remove rows with negative values in them from v
v_new = v[v.min(axis=1)>=0,:]
print(v_new.shape)


(6040, 3)
(6039, 3)


In [20]:
train = pd.read_csv('data/Train.csv')
user_map, item_map = get_user_and_item_map(train)
train = transform_data_to_internal_indexes(train, user_map, item_map)
print(train.shape)
# drop duplicates oh
train = train.drop_duplicates(subset=[USER_COL, ITEM_COL])
print(train.shape)

(859395, 3)
(859395, 3)


In [27]:
# create random matrix with shape (3,3)
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,3)

c = np.outer(b,b)
c

array([[81, 63, 27],
       [63, 49, 21],
       [27, 21,  9]])

In [29]:
a+a

array([[18, 16,  8],
       [14, 14, 12],
       [16, 10, 18]])

In [30]:
a=[(1,2),(3,4)]

In [31]:
for item in a:
    print(item)

(1, 2)
(3, 4)
